### ISSUE TITLE
Referencias a URLs inaccesibles sin usuario y contraseña en el pom.xml

### ISSUE THREAD

**Issue by carreraj** [universitatjaumei/goc#1]
El pom.xml contiene referencias a URLs de uji.es que no son accesibles sin usuario y contraseña e interrumpen la ejecución de maven, imposibilitando la instalación por terceros.

**Comment by borillo** [comment]
Hola @carreraj, ¿Que referencias?

**Comment by carreraj** [comment]
Lineas 57 a 60 contienen referencias a http://jira.uji.es/repos/uji/GOC/goc/trunk y piden usuario y contraseña.

**Comment by borillo** [comment]
La parte del SCM sólo se usa en el proceso de release, pero si bajas el código simplemente del repo y ejecutas "mvn -DskipTests clean package", por ejemplo, para construir el WAR no se usan.

¿Que comando ejecutas para que se haga uso de esta sección?

**Comment by carreraj** [comment]
Es probable que me haya liado. 
Cuando ejecuto "mvn -DskipTests clean package" se produce un error 
`[ERROR] Failed to execute goal org.codehaus.mojo:properties-maven-plugin:1.0-alpha-2:read-project-properties (default) on project goc-base: Properties file not found: /home/carreraj/proyectos/goc/goc/goc-base/${goc.home}/app.properties -> [Help 1]`

Si ejecuto  mvn <goals> -rf :goc-base para retomar la compilación aparece :
`[ERROR] Failed to execute goal on project goc-base: Could not resolve dependencies for project es.uji.apps.goc:goc-base:war:0.1.0-SNAPSHOT: Failure to find es.uji.apps.goc:goc-core:jar:0.1.0-SNAPSHOT in http://devel.uji.es/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of uji has elapsed or updates are forced -> [Help 1]`

Claro que seguramente sea un efecto colateral del primer fallo de compilación.

**Comment by carreraj** [comment]
Ok, parece que me he saltado el paso de establecer la ruta al app.properties.

Mil perdones.

**Comment by borillo** [comment]
No problem!! :)
