### ISSUE TITLE
Poder convocar reuniones sin orden del día

### ISSUE THREAD

**Issue by nmanero** [universitatjaumei/goc#2]
Valorar la posibilidad de poder convocar una reunión sin un orden del día aún fijado, el cuál se añadiría con posterioridad

**Comment by borillo** [comment]
Resulta interesante, pero se debería de poder configurar a nivel de cada órgano para evitar errores en órganos que sí que deben obligatoriamente definir un orden del día @nmanero.

**Comment by borillo** [comment]
Creada historia de usuario de seguimiento en el backlog interno: http://jira.uji.es/browse/GOC-353
