### ISSUE TITLE
Migración del esquema de BBDD Oracle a PostgreSQL

### ISSUE THREAD

**Issue by sergiogragera** [universitatjaumei/goc#3]

**Comment by rmengod** [comment]
No hay problema en generar el esquema para PostgreSQL siempre y cuando el mantenimiento se siga haciendo también en Oracle que es la base de datos por defecto de nuestra universidad.

**Comment by AndresValles** [comment]
Estoy de acuerdo con Raúl, se tiene que seguir manteniendo la versión de Oracle. Nosotros sólo usamos Oracle.

**Comment by nmanero** [comment]
La idea era mantener ambas, no tanto en código java, puesto que ya está desacoplada la base de datos, pero sí en los scripts SQL de creación y modificación de tablas.
Puesto que esto incrementaría el trabajo vuestro, a la hora de aportar mejoras que impliquen cambios en base de datos, por el momento la dejamos estar
